name: Continuous Integration
on: pull_request

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Run unit tests
        run: pnpm test
      - name: Run TypeScript check
        run: pnpm tsc
  lint:
    name: Run ESLint with Reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: pnpm lint
      - name: Install eslint-formatter-rdjson
        run: pnpm add -D eslint-formatter-rdjson
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run ESLint with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm eslint -f rdjson . | reviewdog -f=rdjson -reporter=github-pr-review
